resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      slowCallDurationThreshold: 1500 #1.5 secs
      failureRateThreshold: 40
      eventConsumerBufferSize: 10
      record-exceptions:
        - com.paprotskyi.twostatecircuitbreaker.exception.FailResponseException
        - java.lang.InterruptedException

logging:
  level:
    root: info

number-of-test-calls: 100
test-mode: success_rate_traditional #success_rate_threshold


# trad 063 063
# mine 019 019 046 047 046 !!!!074!!!!

#trad (20) 0.65 !!!0.51!!!
#mine new (15)0.39 (20)0.61 !!!0.61!!!
