resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 1 #this enables the thresholds check starting from the first request
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 3s
      slowCallDurationThreshold: 5000 #5 secs
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      record-exceptions:
        - com.paprotskyi.twostatecircuitbreaker.exception.FailResponseException
        - java.lang.InterruptedException

logging:
  level:
    root: info

number-of-test-calls: 100

